name: k8app
services:
  backend:
    build:
      context: /home/lazarus/Repos/k8app/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: "false"
    container_name: k8app-backend
    depends_on:
      db:
        condition: service_started
    environment:
      BACKEND_CORS_ORIGINS: '["http://localhost","http://localhost:1337", "http://localhost:4200",
        "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200",
        "https://localhost:3000", "https://localhost:8080", "http://dev.k8app.com",
        "https://stag.k8app.com", "https://k8app.com", "http://local.dockertoolbox.tiangolo.com",
        "http://localhost.tiangolo.com"]'
      DOCKER_IMAGE_BACKEND: k8app-backend-image
      DOCKER_IMAGE_FRONTEND: k8app-frontend-image
      DOMAIN: localhost
      FIRST_SUPERUSER: admin@k8app.com
      FIRST_SUPERUSER_PASSWORD: pass
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pass
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      PROJECT_NAME: k8app
      SECRET_KEY: 99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f
      SERVER_HOST: https://localhost
      SERVER_NAME: localhost
      STACK_NAME: k8app-com
      TAG: "1.1"
    image: k8app-backend-image:1.1
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "8080"
      protocol: tcp
  db:
    container_name: k8app-db
    environment:
      BACKEND_CORS_ORIGINS: '["http://localhost","http://localhost:1337", "http://localhost:4200",
        "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200",
        "https://localhost:3000", "https://localhost:8080", "http://dev.k8app.com",
        "https://stag.k8app.com", "https://k8app.com", "http://local.dockertoolbox.tiangolo.com",
        "http://localhost.tiangolo.com"]'
      DOCKER_IMAGE_BACKEND: k8app-backend-image
      DOCKER_IMAGE_FRONTEND: k8app-frontend-image
      DOMAIN: localhost
      FIRST_SUPERUSER: admin@k8app.com
      FIRST_SUPERUSER_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pass
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      PROJECT_NAME: k8app
      SECRET_KEY: 99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f
      SERVER_HOST: https://localhost
      SERVER_NAME: server
      STACK_NAME: k8app-com
      TAG: "1.1"
    image: postgres:12
    networks:
      default: null
    ports:
    - mode: ingress
      target: 5432
      published: "5432"
      protocol: tcp
    volumes:
    - type: volume
      source: app-db-data
      target: /var/lib/postgresql/data/pgdata
      volume: {}
  frontend:
    build:
      context: /home/lazarus/Repos/k8app/frontend
      dockerfile: frontend.dockerfile
    container_name: k8app-frontend
    depends_on:
      backend:
        condition: service_started
    image: k8app-frontend-image:1.1
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "1337"
      protocol: tcp
networks:
  default:
    name: k8app_default
volumes:
  app-db-data:
    name: k8app_app-db-data
    driver: local
