apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-fastapi-container
          image: k8app-backend-image:1.1
          imagePullPolicy: Never # get image locally. for imagePullPolicy: Never the images need to be on the minikube node.
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - configMapRef:
                name: postgres-config # populate db-specific values (needed to keep one source of truth)
#            - secretRef: # This does not work and results in userinfo required in URL but missing
#                name: postgres-secret # populate db-specific secrets (needed to keep one source of truth)
# TODO: fix this issue. Maybe its because of improper decoding of password (There is an redundant \n in prints)