apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-fastapi-container
          image: k8app-backend-image:1.1
          imagePullPolicy: Never # get image locally. for imagePullPolicy: Never the images need to be on the minikube node.
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
#            - secretRef:
#                name: postgres-secret
#          env:
#            - name: POSTGRES_SERVER
#              value: postgres-service:5432