apiVersion: v1
kind: Service
metadata:
  name: lb-backend
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  selector:
    app: backend
