apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: backend.k8app.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: lb-backend
            port:
              number: 80