kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "k8app-chart.fullname" . }}-backend-network-policy
spec:
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443