apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8app-frontend
spec:
  selector:
    matchLabels:
      app: k8app-frontend
  template:
    metadata:
      labels:
        app: k8app-frontend
        role: frontend
    spec:
      containers:
        - name: k8app-frontend
          image: dangg/k8app-frontend-image
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          envFrom:
            - configMapRef:
                name: k8app-frontend-config
