apiVersion: v1
kind: Service
metadata:
  name: k8app-frontend
spec:
  selector:
    app: k8app-frontend
  ports:
  - port: 3001
    name: http    
    targetPort: 80
  - port: 4001
    name: https
    targetPort: 443
  type: LoadBalancer