apiVersion: v1
kind: Service
metadata:
  labels:
    apps: backend
  name: backend
spec:
  type: ClusterIP
  ports:
  - name: "backend-service"
    port: 8080
    targetPort: 80
  selector:
    app: backend