apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: backend
  name: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata: 
      labels:
        app: backend
    spec:
      containers:
      - name: backend-pod
        image: nader2929/sc_course:k8app-backend-image
        ports:
        - containerPort: 80
          hostPort: 8080
        envFrom:
          - configMapRef:
              name: k8app-configs
        env:
        - name: SERVER_NAME
          value: localhost
        - name: SERVER_HOST
          value: https://localhost
        imagePullPolicy: IfNotPresent