apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: db
  template:
    metadata: 
      labels:
        app: db
    spec:
      containers:
      - name: db-pod
        image: postgres:12
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: k8app-configs
        # volumeMounts:
        # - mountPath: /var/lib/postgresql/data/pgdata
        #   name: app-db-data
      volumes:
      - name: app-db-data
        emptyDir: {}