apiVersion: v1
kind: Service
metadata:
  labels:
    apps: frontend
  name: frontend
spec:
  type: ClusterIP
  ports:
  - name: "frontend-service"
    port: 1337
    targetPort: 80
  selector:
    app: frontend