apiVersion: v1
data:
  BACKEND_CORS_ORIGINS: '["http://localhost","http://localhost:1337", "http://localhost:4200",
    "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200",
    "https://localhost:3000", "https://localhost:8080", "http://dev.k8app.com", "https://stag.k8app.com",
    "https://k8app.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  DOCKER_IMAGE_BACKEND: k8app-backend-image
  DOCKER_IMAGE_FRONTEND: k8app-frontend-image
  DOMAIN: localhost
  FIRST_SUPERUSER: admin@k8app.com
  FIRST_SUPERUSER_PASSWORD: pass
  POSTGRES_DB: app
  POSTGRES_PASSWORD: pass
  POSTGRES_SERVER: db
  POSTGRES_USER: postgres
  PROJECT_NAME: k8app
  SECRET_KEY: 99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f
  SERVER_HOST: https://localhost
  SERVER_NAME: server
  STACK_NAME: k8app-com
  TAG: "1.1"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-15T11:15:59Z"
  name: k8app-configs
  namespace: default
  resourceVersion: "67114"
  uid: e115904a-7deb-4872-ad11-1cc82736314b
