apiVersion: v1
kind: Service
metadata:
  name: k8app-backend
spec:
  type: LoadBalancer
  selector:
    app: k8app-backend
  ports:
  - protocol: TCP
    nodePort: 30002
    port: 3000
    targetPort: 80