apiVersion: v1
kind: Service
metadata:
  name: k8app-frontend
spec:
  type: LoadBalancer
  selector:
    app: k8app-frontend
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 3001
    targetPort: 80
